name: Upsella README

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "content/**.md"
      - "!content/**index.md"

jobs:
  sync:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-sync
    steps:
      - name: "Checkout This repo"
        uses: actions/checkout@v3
        with:
          path: main

      - name: "Checkout Upsella repo"
        uses: actions/checkout@v3
        with:
          repository: upsella/online
          path: sandboxes
          token: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}

      - name: "Prepare git info"
        id: git_info
        run: |
          echo "::set-output name=git_sha::$(echo $GITHUB_SHA | cut -c-7)"
          echo "::set-output name=user_name::${{ github.event.head_commit.author.name || github.actor }}"
          echo "::set-output name=user_email::${{ github.event.head_commit.author.email || format('{0}@users.noreply.github.com', github.actor) }}"

      - name: "Push updates"
        run: |
          git -C sandboxes config user.name ${{ steps.git_info.outputs.user_name }}
          git -C sandboxes config user.email ${{ steps.git_info.outputs.user_email }}
          git -C sandboxes add .
          git -C sandboxes commit -m "Update READMEs ${{ github.repository }}@${{ steps.git_info.outputs.git_sha }}"
          git -C sandboxes push
